config/routes.rb
Rails.application.routes.draw do

  # verb 'url' hashrocket 'controller#method'

  get '/books' => 'book#index', as: 'books'
  get '/books/new' => 'book#new', as: 'new_book'
  get '/books/:id' => 'book#show', as: 'book'
  post '/books' => 'book#create'
  get 'books/:id/edit' => 'book#edit', as: 'edit_book'
  patch 'books/:id' => 'book#update'
  delete '/books/:id' => 'book#destroy', as: 'delete_book'

  # Defines the root path route ("/")
   root "book#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/book.rb
class Book < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/book_controller.rb
class BookController < ApplicationController

  def index
    @books = Book.all
  end

  def show
    # params gives us access to the url which will have an id
    @book = Book.find(params[:id])
  end

  def new
    @book = Book.new 
  end

  def create
    @book = Book.create(book_params)
      if @book.valid?
        redirect_to books_path
      end
  end

  def edit
    @book = Book.find(params[:id])
  end

  def update 
    @book = Book.find(params[:id])
    if @book.update(book_params)
      redirect_to book_path(@book)
    end
  end

  def destroy
    @book = Book.find(params[:id])
    if @book.destroy
      redirect_to books_path
    end
  end

  # strong params
  private
   def book_params
    params.require(:book).permit(:name, :read)
   end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/book_helper.rb
module BookHelper
end

app/views/book/edit.html.erb
<h2>Edit Book</h2>
<%= form_with model: @book, method: :patch do |form| %>
  <%= form.label :name %>
  <%= form.text_field :name %>
  <br><br>
  <%= form.label :read %>
  <%= form.text_field :read %>
  <br><br>
  <%= form.submit "Edit Book" %>
<% end %>

<p>
  <%= link_to 'Back to Home', books_path %>
</p>

app/views/book/index.html.erb
<h1>My Reading Tracker</h1>
<ul>
  <%# take array holding all the books, loop over it to access each book %>
  <% @books.each do |book| %>
  <%# on each iteration of the loop, we are printing the name of that book to the screen %>
  <li><%= link_to book.name, book_path(book) %></li>
  <% end %>
 </ul>
 <%= link_to 'Add a Book', new_book_path %>

app/views/book/new.html.erb
<h3>Add a New Book</h3>
<%= form_with model: @book do |form| %>
  <%= form.text_field :name %>
  <br/><br/>
  <%= form.text_area :read %>
   <br/><br/>
  <%= form.submit %>
<% end %>

app/views/book/show.html.erb
<h3><%= @book.name %></h3>
<h4> Have I read this book:  <%= @book.read %> </h4>
<br />
<%= link_to 'Update Book',
    edit_book_path(@book) %>
    <br/><br/>
<%= button_to 'Remove Book', delete_book_path, method: 'delete' %>
<br/>

<%= link_to 'Back to Books', books_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FullStackRails</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>